export default {
        ChatCar:{
            selectedImg:'https://www.swsai.com/style/dist/img/icon/Frame9.png',
            unselectedImg:'https://www.swsai.com/style/dist/img/icon/Frame8_1.png'
        },
        智能搜索:{
            selectedImg:'https://www.swsai.com/style/dist/img/icon/Frame15.png',
            unselectedImg:'https://www.swsai.com/style/dist/img/icon/Frame15_2.png'
        },
        文案生成:{
            selectedImg:'https://www.swsai.com/style/dist/img/icon/Frame14.png',
            unselectedImg:'https://www.swsai.com/style/dist/img/icon/Frame14_2.png'
        },
        图片生成:{
            selectedImg:'https://www.swsai.com/style/dist/img/icon/Frame13.png',
            unselectedImg:'https://www.swsai.com/style/dist/img/icon/Frame13_1.png'
        },
        视频生成:{
            selectedImg:'https://www.swsai.com/style/dist/img/icon/Frame12.png',
            unselectedImg:'https://www.swsai.com/style/dist/img/icon/Frame12_1.png'
        },
        最近生成:{
            selectedImg:'https://www.swsai.com/style/dist/img/icon/Frame10.png',
            unselectedImg:'https://www.swsai.com/style/dist/img/icon/Frame10_1.png'
        },
        收藏夹:{
            selectedImg:'https://www.swsai.com/style/dist/img/icon/Frame11.png',
            unselectedImg:'https://www.swsai.com/style/dist/img/icon/Frame11_1.png'
        },
}
